apiVersion: v1
kind: ConfigMap
metadata:
  name: naki-customer-management-config
  namespace: naki
data:
  APP_HTTP_PORT: "5083"
  BEEGO_RUNMODE: "prod"
  DB_HOST: "postgres-platform.nakilink.postgres.database.azure.com"
  DB_PORT: "5432"
  DB_NAME: "customer_management_test"
  DB_SSLMODE: "require"
