apiVersion: v1
kind: Secret
metadata:
  name: naki-customer-management-secrets
  namespace: naki
type: Opaque
stringData:
  DB_USER: "pgadmin"
  DB_PASSWORD: "eQual1z3rR"
  JWT_SECRET_KEY: "CHANGE_ME_TO_A_STRONG_SECRET"
