apiVersion: v1
kind: Service
metadata:
  name: naki-customer-management-service
  namespace: naki
spec:
  selector:
    app: naki-customer-management-service
  ports:
    - name: http
      port: 80
      targetPort: 5083
      protocol: TCP
  type: ClusterIP
